import {
  User,
  UserRole,
  Plan,
  PlanTier,
  Partner,
  PartnerType,
  PartnerStatus,
  Company,
  Employee,
  CheckIn,
  Invoice,
  Analytics,
} from '../types';

// Test accounts
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'employee@test.com',
    name: 'Ahmad Ali',
    role: UserRole.EMPLOYEE,
    companyId: 'company-1',
    companyCode: 'ABC123',
    planId: 'plan-2',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    email: 'hr@test.com',
    name: 'Sarah Mohammed',
    role: UserRole.COMPANY_ADMIN,
    companyId: 'company-1',
    companyCode: 'ABC123',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-3',
    email: 'admin@test.com',
    name: 'Platform Admin',
    role: UserRole.PLATFORM_ADMIN,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

// Default password for all test accounts: Test@12345
export const TEST_PASSWORD = 'Test@12345';

// Plans
export const mockPlans: Plan[] = [
  {
    id: 'plan-1',
    tier: PlanTier.BRONZE,
    name: 'Bronze',
    monthlyPrice: 199,
    checkInsPerMonth: 8,
    includedCategories: ['Gym'],
    description: 'Perfect for getting started with wellness',
  },
  {
    id: 'plan-2',
    tier: PlanTier.SILVER,
    name: 'Silver',
    monthlyPrice: 399,
    checkInsPerMonth: 16,
    includedCategories: ['Gym', 'Spa'],
    description: 'Great balance of value and variety',
  },
  {
    id: 'plan-3',
    tier: PlanTier.GOLD,
    name: 'Gold',
    monthlyPrice: 599,
    checkInsPerMonth: 30,
    includedCategories: ['Gym', 'Spa', 'Club'],
    description: 'Premium access to all facilities',
  },
  {
    id: 'plan-4',
    tier: PlanTier.CLUB_PLUS,
    name: 'Club+',
    monthlyPrice: 899,
    checkInsPerMonth: 999,
    includedCategories: ['Gym', 'Spa', 'Club', 'Premium'],
    description: 'Unlimited access to exclusive clubs',
  },
  {
    id: 'plan-5',
    tier: PlanTier.DIGITAL,
    name: 'Digital',
    monthlyPrice: 99,
    checkInsPerMonth: 999,
    includedCategories: ['Digital'],
    description: 'Online classes and wellness content',
  },
];

// Partners
export const mockPartners: Partner[] = [
  {
    id: 'partner-1',
    name: 'Fitness First Riyadh',
    type: PartnerType.GYM,
    city: 'Riyadh',
    address: 'King Fahd Road, Riyadh',
    latitude: 24.7136,
    longitude: 46.6753,
    rating: 4.5,
    openHours: '6 AM - 11 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Fitness+First',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-2',
    name: 'Gold\'s Gym Jeddah',
    type: PartnerType.GYM,
    city: 'Jeddah',
    address: 'Tahlia Street, Jeddah',
    latitude: 21.5433,
    longitude: 39.1728,
    rating: 4.7,
    openHours: '5 AM - 12 AM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Golds+Gym',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-3',
    name: 'Spa Essence Riyadh',
    type: PartnerType.SPA,
    city: 'Riyadh',
    address: 'Olaya Street, Riyadh',
    latitude: 24.6877,
    longitude: 46.6859,
    rating: 4.8,
    openHours: '9 AM - 10 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Spa+Essence',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-4',
    name: 'Luxury Spa Jeddah',
    type: PartnerType.SPA,
    city: 'Jeddah',
    address: 'Corniche Road, Jeddah',
    latitude: 21.4858,
    longitude: 39.1925,
    rating: 4.6,
    openHours: '10 AM - 10 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Luxury+Spa',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-5',
    name: 'Elite Club Riyadh',
    type: PartnerType.CLUB,
    city: 'Riyadh',
    address: 'Diplomatic Quarter, Riyadh',
    latitude: 24.6937,
    longitude: 46.6197,
    rating: 4.9,
    openHours: '7 AM - 11 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Elite+Club',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-6',
    name: 'Virtual Wellness Hub',
    type: PartnerType.DIGITAL,
    city: 'Online',
    address: 'Digital Platform',
    latitude: 24.7136,
    longitude: 46.6753,
    rating: 4.4,
    openHours: '24/7',
    imageUrl: 'https://via.placeholder.com/400x300?text=Virtual+Wellness',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'partner-7',
    name: 'PowerHouse Gym Dammam',
    type: PartnerType.GYM,
    city: 'Dammam',
    address: 'King Abdullah Road, Dammam',
    latitude: 26.4367,
    longitude: 50.1037,
    rating: 4.3,
    openHours: '6 AM - 11 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=PowerHouse',
    status: PartnerStatus.PENDING,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'partner-8',
    name: 'Serenity Spa Riyadh',
    type: PartnerType.SPA,
    city: 'Riyadh',
    address: 'Al Malqa, Riyadh',
    latitude: 24.8138,
    longitude: 46.6478,
    rating: 4.7,
    openHours: '10 AM - 9 PM',
    imageUrl: 'https://via.placeholder.com/400x300?text=Serenity+Spa',
    status: PartnerStatus.APPROVED,
    createdAt: '2024-01-15T00:00:00Z',
  },
];

// Companies
export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'Tech Solutions LLC',
    code: 'ABC123',
    adminEmail: 'hr@test.com',
    billingDetails: '123 Tech Street, Riyadh',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'company-2',
    name: 'Digital Innovations',
    code: 'DIG456',
    adminEmail: 'admin@digital.com',
    billingDetails: '456 Innovation Ave, Jeddah',
    status: 'active',
    createdAt: '2024-01-10T00:00:00Z',
  },
];

// Employees
export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Ahmad Ali',
    email: 'employee@test.com',
    companyId: 'company-1',
    planId: 'plan-2',
    status: 'active',
    lastCheckIn: '2024-02-15T10:30:00Z',
    totalCheckIns: 12,
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'emp-2',
    name: 'Fatima Hassan',
    email: 'fatima@tech.com',
    companyId: 'company-1',
    planId: 'plan-3',
    status: 'active',
    lastCheckIn: '2024-02-14T15:20:00Z',
    totalCheckIns: 18,
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'emp-3',
    name: 'Mohammed Ibrahim',
    email: 'mohammed@tech.com',
    companyId: 'company-1',
    planId: 'plan-1',
    status: 'active',
    lastCheckIn: '2024-02-13T09:15:00Z',
    totalCheckIns: 7,
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'emp-4',
    name: 'Layla Ahmed',
    email: 'layla@tech.com',
    companyId: 'company-1',
    status: 'invited',
    totalCheckIns: 0,
    createdAt: '2024-02-10T00:00:00Z',
  },
];

// Check-ins
export const mockCheckIns: CheckIn[] = [
  {
    id: 'checkin-1',
    userId: 'user-1',
    partnerId: 'partner-1',
    partnerName: 'Fitness First Riyadh',
    timestamp: '2024-02-15T10:30:00Z',
    qrToken: 'token-123',
  },
  {
    id: 'checkin-2',
    userId: 'user-1',
    partnerId: 'partner-3',
    partnerName: 'Spa Essence Riyadh',
    timestamp: '2024-02-12T14:20:00Z',
    qrToken: 'token-124',
  },
  {
    id: 'checkin-3',
    userId: 'user-1',
    partnerId: 'partner-1',
    partnerName: 'Fitness First Riyadh',
    timestamp: '2024-02-10T08:15:00Z',
    qrToken: 'token-125',
  },
  {
    id: 'checkin-4',
    userId: 'user-1',
    partnerId: 'partner-5',
    partnerName: 'Elite Club Riyadh',
    timestamp: '2024-02-08T18:45:00Z',
    qrToken: 'token-126',
  },
];

// Invoices
export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    companyId: 'company-1',
    invoiceNumber: 'INV-2024-001',
    date: '2024-02-01T00:00:00Z',
    amount: 15960,
    status: 'paid',
    pdfUrl: '/api/invoices/inv-1/pdf',
  },
  {
    id: 'inv-2',
    companyId: 'company-1',
    invoiceNumber: 'INV-2024-002',
    date: '2024-01-01T00:00:00Z',
    amount: 15960,
    status: 'paid',
    pdfUrl: '/api/invoices/inv-2/pdf',
  },
];

// Analytics
export const mockAnalytics: Analytics = {
  totalCheckIns: 1247,
  activeUsers: 156,
  activeCompanies: 12,
  checkInsOverTime: [
    { date: '2024-02-08', count: 45 },
    { date: '2024-02-09', count: 52 },
    { date: '2024-02-10', count: 48 },
    { date: '2024-02-11', count: 61 },
    { date: '2024-02-12', count: 55 },
    { date: '2024-02-13', count: 58 },
    { date: '2024-02-14', count: 63 },
    { date: '2024-02-15', count: 71 },
  ],
};
